// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhsaM5kk-PMeL2kGDLtfHjY9gSdUQWNWo',
    appId: '1:862816404461:web:0ecbe3caee9c9839bbdde4',
    messagingSenderId: '862816404461',
    projectId: 'metaozce2023',
    authDomain: 'metaozce2023.firebaseapp.com',
    storageBucket: 'metaozce2023.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM6zUw67cR1gvs6DP5_nplXjBe-hhdfQ4',
    appId: '1:862816404461:android:97d21d95da62ab44bbdde4',
    messagingSenderId: '862816404461',
    projectId: 'metaozce2023',
    storageBucket: 'metaozce2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJY5WdYfPFNaxSFD549-av7VsWMihVJI0',
    appId: '1:862816404461:ios:5475e9cf3d3dae19bbdde4',
    messagingSenderId: '862816404461',
    projectId: 'metaozce2023',
    storageBucket: 'metaozce2023.appspot.com',
    iosClientId: '862816404461-igijjocuerd65s78vrv26735ua5v8ppv.apps.googleusercontent.com',
    iosBundleId: 'com.example.metaOzce0',
  );
}
